# Generated by Django 5.0.6 on 2024-06-13 03:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs Nomi', max_length=100)),
                ('started', models.DateTimeField(help_text='Kurs Boshlanishi')),
                ('duration', models.IntegerField(default=0, help_text='Kurs Davomiligi')),
                ('description', models.TextField(blank=True, help_text='Kurs haqida', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text=' Bir Oylik Kurs Narxi', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs Mavzusi', max_length=100)),
                ('video', models.FileField(upload_to='theme/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'ASF', 'FLV', 'MKV', 'MOV'])])),
                ('description', models.TextField(blank=True, help_text='Kurs haqida', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Izoh')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('coursetheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetheme')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeordislike', models.BooleanField()),
                ('coursetheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetheme')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
