# Generated by Django 5.0.6 on 2024-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetheme',
            name='description',
            field=models.TextField(blank=True, help_text='Mavzu haqida', null=True),
        ),
    ]
